# version of the circleCI used
version: 2.1

# command lines that circleCI provides
orbs:
    node: circleci/node@5.0.1
# Define a job to be invoked later in a workflow.
jobs:
    go-to-work:
        docker:
            - image: cimg/base:stable
        steps:
            - checkout
            - run:
                  name: 'Wake up'
                  command: 'echo Wake up'
            - run:
                  name: 'Have breakfast'
                  command: 'echo Have breakfast'
            - run:
                  name: 'Go to work'
                  command: 'echo Go to work'

workflows:
    say-hello-workflow:
        jobs:
            - say-hello
