name: Build
on:
    pull_request_review:
        types: [submitted]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci
            - name: Save NPM cache
              uses: actions/cache@v2
              with:
                  path: ~/.cache/npm
                  key: npm-cache-${{ hashFiles('package-lock.json') }}
                  restore-keys: npm-cache-
            - name: Run tests
              run: npm test

    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Trigger Build workflow on CircleCI
              run: |
                  curl \
                      -X POST \
                      -H "Content-Type: application/json" \
                      -H "Circle-Token: ${{ secrets.CIRCLECI_TOKEN }}" \
                      --data '{"branch": "develop", "parameters": {"task": "build"}}' \
                      https://circleci.com/api/v2/project/gh/High10Hunter/express-example/pipeline
