name: prevent secrets
on:
    push:
        paths:
            - '**.js'
        branches:
            - 'main'
    pull_request:
        types: [opened, synchronize, labeled, unlabeled]
jobs:
    prevent-secrets:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: echo This is repo secret ${{ secrets.DB_PASSWORD }}
